allow_origins:
  - "https://cin114.net"
  - "https://dev.cin114.net"
  - "http://localhost:3000"
allow_methods:
  - "GET"
  - "POST"
  - "DELETE"
  - "OPTIONS"
  - "PUT"
  - "PATCH"
allow_headers:
  - "Origin"
  - "Authorization"
  - "Content-Type"
  - "Accept"
expose_headers:
  - "Content-Length"
allow_credentials: true
allow_origin_func:
  - "https://cin114.net"
  - "https://dev.cin114.net"
  - "http://localhost:3000"
max_age: 3600 
