allow_origins:
  - "https://cin114.net"
  - "https://www.cin114.net"
  - "https://cin114films.com"
  - "https://www.cin114films.com"
  - "https://api.cin114.net"
  - "https://dev.cin114.net"
  - "https://dev.api.cin114.net"
  - "https://api.dev.cin114.net"
  - "http://localhost:3000"
  - "http://localhost:3030"
allow_methods:
  - "GET"
  - "POST"
  - "DELETE"
  - "OPTIONS"
  - "PUT"
  - "PATCH"
allow_headers:
  - "Origin"
  - "Authorization"
  - "Content-Type"
  - "Accept"
expose_headers:
  - "Content-Length"
allow_credentials: true
max_age: 3600 
