version: '3'

services:
  nextjs:
    container_name: cin114 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: nextjs 
    volumes:
      - ./:/usr/src/app
    environment:
      - GO_ENV=development
    command: npm run dev
  nginx:
    container_name: cin114-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/default:/etc/nginx/sites-available/
    depends_on:
      - nextjs

