version: '3'

services:
  nextjs:
    container_name: cin114 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: nextjs 
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules #ignore 
      - /usr/src/app/.next #ingore 
    #never shut down the container, always restart
    restart: unless-stopped 
    command: npm start 
  nginx:
    container_name: cin114-nginx
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - nextjs

