version: '3.8'

services:
  nextjs:
    image: ghcr.io/identityofsine/cin114:dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://dev.cin114.net
      - NEXT_PUBLIC_BRANCH=dev
    ports:
      - "3001:3000"  # Different port for dev

  api:
    image: ghcr.io/identityofsine/cin114-api:dev
    environment:
      - GO_ENV=development
      - URI=https://dev.cin114.net/
      - DOMAIN=dev.cin114.net
      - FRONTEND_URI=https://dev.cin114.net/
      - CORS_ALLOWED_ORIGINS=https://dev.cin114.net
    ports:
      - "3030:3001"
