services:
  nextjs:
    image: ghcr.io/identityofsine/cin114:dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://dev.cin114.net
      - NEXT_PUBLIC_BRANCH=dev
    ports:
      - "3001:3000"  # Different port for dev
    networks:
      - cin114-network

  api:
    image: ghcr.io/identityofsine/cin114-api:dev
    environment:
      - GO_ENV=development
      - PORT=3030
      - URI=https://dev.cin114.net/
      - DOMAIN=dev.cin114.net
      - FRONTEND_URI=https://dev.cin114.net/
      - CORS_ALLOWED_ORIGINS=https://dev.cin114.net
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_NAME=app
      - DB_SSL_MODE=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cin114-network

  # PostgreSQL Database
  db:
    container_name: cin114-database-dev
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_INITDB_ARGS=--auth-local=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - cin114-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  cin114-network:
    driver: bridge
    external: true
    name: cin114-net

