services:
  # NextJS Frontend - Development
  nextjs-dev:
    container_name: cin114-dev-frontend
    image: ghcr.io/identityofsine/cin114:dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BRANCH=dev
      - NEXT_PUBLIC_API_URL=https://dev.cin114.net
      - NEXT_PUBLIC_API_BASE_URL=https://api.dev.cin114.net
      - BASE_URL=https://dev.cin114.net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    hostname: devnextjs
    restart: unless-stopped
    depends_on:
      - api-dev
    networks:
      - cin114-net

  # Go Backend API - Development
  api-dev:
    container_name: cin114-dev-api
    image: ghcr.io/identityofsine/cin114-api:dev
    environment:
      - GO_ENV=development
      - NODE_ENV=development
      - PORT=3030
      - URI=https://dev.cin114.net/
      - DOMAIN=dev.cin114.net
      - FRONTEND_URI=https://dev.cin114.net/
      - CORS_ALLOWED_ORIGINS=https://dev.cin114.net
      - DB_HOST=db-dev
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_NAME=app
      - DB_SSL_MODE=disable
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_placeholder}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_placeholder}
      - STRIPE_REDIRECT_URL=${STRIPE_REDIRECT_URL:-https://dev.cin114.net}
      - BUILD_DATE=${BUILD_DATE:-}
      - BUILD_ID=${BUILD_ID:-}
      - GIT_COMMIT=${GIT_COMMIT:-}
      - GIT_BRANCH=${GIT_BRANCH:-}
      - VERSION=${VERSION:-}
    hostname: devapi
    restart: unless-stopped
    depends_on:
      db-dev:
        condition: service_healthy
    networks:
      - cin114-net
      - dev-only

  # PostgreSQL Database - Development
  db-dev:
    container_name: cin114-dev-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_INITDB_ARGS=--auth-local=trust
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - dev-only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data_dev:
    driver: local

networks:
  dev-only:
    driver: bridge
    name: dev-only
  cin114-net:
    driver: bridge
    external: true
    name: cin114-net

