version: '3'

services:
  api:
    container_name: cin114-backend-dev-serve
    environment:
      - GO_ENV=development
      - URI=https://dev.cin114.net/
      - DOMAIN=dev.cin114.net
      - FRONTEND_URI=https://dev.cin114.net/
      - PORT=3001
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_NAME=app
    command: go run cmd/server/main.go
    build: 
      context: .
      dockerfile: Dockerfile.local
    restart:
      always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: cin114-backend-dev-serve-db
    image: postgres:latest 
    restart: always
    tty: true
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


