version: '3'

services:
  api:
    container_name: cin114-backend-dev
    environment:
      - GO_ENV=development
      - URI=http://localhost:3030/
      - DOMAIN=localhost
      - FRONTEND_URI=http://localhost:3000/
      - PORT=3030
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_NAME=app
      - DB_HOST=db
    command: nodemon -L --legacy-watch --exec go run cmd/server/main.go --signal SIGTERM
    ports:
      - "3030:3030"
    build: 
      context: .
      dockerfile: Dockerfile.local
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: cin114-backend-dev-db
    image: postgres:latest 
    restart: always
    tty: true
    ports:
      - "5555:5432"
    volumes:
      - ./dev-data/sql:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
