name: Test, Build, and Deploy to Production Environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FRONTEND_IMAGE: ghcr.io/identityofsine/cin114
  API_IMAGE: ghcr.io/identityofsine/cin114-api
  TAG: prod

permissions:
  packages: write

jobs:

  test:
    name: Test
    uses: ./.github/workflows/test:frontend.yml

  build-and-push:
    name: Build and Push Docker Images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set build environment variables
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BRANCH=prod" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.TAG }} \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg BUILD_ID=${{ env.BUILD_ID }} \
            --build-arg NEXT_PUBLIC_BRANCH=${{ env.NEXT_PUBLIC_BRANCH }} \
            -f Dockerfile .

      - name: Build API Docker image
        run: |
          docker build -t ${{ env.API_IMAGE }}:${{ env.TAG }} \
            -f backend/Dockerfile ./backend

      - name: Push Frontend Docker image
        run: docker push ${{ env.FRONTEND_IMAGE }}:${{ env.TAG }}

      - name: Push API Docker image
        run: docker push ${{ env.API_IMAGE }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Execute deployment script 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          set -x  # Print each command before executing it
          # Navigate to the homebrew directory
          cd ~/homebrew || exit 1
          ./deploy.sh prod
