name: Test, Build, and Deploy to Production Environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/identityofsine/cin114
  TAG: prod  # change to 'prod' for production branch


jobs:

  test:
    name: Test
    uses: ./.github/workflows/test:frontend.yml

  build-and-push:
    name: Build and Push Docker Image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set build environment variables
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo 'NEXT_PUBLIC_BRANCH="prod"' >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker compose build \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg BUILD_ID=${{ env.BUILD_ID }} \
            --build-arg NEXT_PUBLIC_BRANCH=${{ env.NEXT_PUBLIC_BRANCH }}

      - name: Push Docker image
        run: docker compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Execute deployment script 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          set -x  # Print each command before executing it
          # Navigate to the homebrew directory
          cd ~/homebrew || exit 1
          ./deploy.sh prod
