name: Test, Build, and Deploy to Development Environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/kcosine/cin114
  TAG: prod  # change to 'prod' for production branch

jobs:

  test:
    name: Test and Build
    uses: ./.github/workflows/test:frontend.yml

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Execute deployment script 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          set -x  # Print each command before executing it
          # Navigate to the homebrew directory
          cd ~/homebrew || exit 1
          # Run the deployment script with the 'dev' argument
          ./deploy.sh dev
