name: Test, Build, and Deploy to Development Environment

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

env:
  FRONTEND_IMAGE: ghcr.io/identityofsine/cin114
  API_IMAGE: ghcr.io/identityofsine/cin114-api
  TAG: dev

permissions:
  packages: write

jobs:

  debug-secrets:
    name: Debug - Check Secrets Access
    runs-on: ubuntu-latest
    steps:
    - name: Debug - Check if secrets are accessible
      run: |
        echo "Testing secret access..."
        echo "SERVER_IP is set: ${{ secrets.SERVER_IP != '' }}"
        echo "SERVER_USER is set: ${{ secrets.SERVER_USER != '' }}"
        echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
        echo "SERVER_USER value: ${{ secrets.SERVER_USER }}"
        echo "SERVER_IP length: ${#SERVER_IP}"
        echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  test:
    name: Test
    uses: ./.github/workflows/test:frontend.yml

  build-and-push:
    name: Build and Push Docker Images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set build environment variables
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BRANCH=dev" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.TAG }} \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg BUILD_ID=${{ env.BUILD_ID }} \
            --build-arg NEXT_PUBLIC_BRANCH=${{ env.NEXT_PUBLIC_BRANCH }} \
            -f Dockerfile .

      - name: Build API Docker image
        run: |
          docker build -t ${{ env.API_IMAGE }}:${{ env.TAG }} \
            -f backend/Dockerfile ./backend

      - name: Push Frontend Docker image
        run: docker push ${{ env.FRONTEND_IMAGE }}:${{ env.TAG }}

      - name: Push API Docker image
        run: docker push ${{ env.API_IMAGE }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Deploy to Development
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          set -x  # Print each command before executing it
          # Set environment variables for deployment
          export NEXT_PUBLIC_BRANCH="dev"
          export NODE_ENV="development"
          export BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          export BUILD_ID="$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
          # Navigate to the homebrew directory
          cd ~/homebrew || exit 1
          # Run the NEW streamlined deployment script
          ./deploy-new.sh dev

