name: Test, Build, and Deploy to Development Environment

on:
  push:
    branches: ["main", "develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key in GitHub secrets

    - name: Run deployment script
      run: |
        ssh -o StrictHostKeyChecking=no {{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'bash -s' < './homebrew/deploy.sh dev'
      continue-on-error: false  # This ensures that if the SSH command fails, the job fails
