name: Test, Build, and Deploy to Development Environment

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:

  test:
    uses: ./.github/workflows/test:frontend.yml

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Execute deployment script 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          set -x  # Print each command before executing it
          # Navigate to the homebrew directory
          cd ~/homebrew || exit 1
          # Run the deployment script with the 'dev' argument
          ./deploy.sh dev
